# Generated by Django 5.0.6 on 2024-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigoVenta', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=18)),
                ('producto', models.ManyToManyField(to='api.producto')),
                ('venta', models.ManyToManyField(to='api.venta')),
            ],
        ),
    ]
